name: test
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        working-directory: ./client
        run: yarn
      - name: Check types
        working-directory: ./client
        run: yarn typecheck
      - name: Run backend
        working-directory: ./
        run: docker-compose -f docker-compose.yaml up --build -d
      - name: Show logs
        if: ${{ failure() }}
        run: docker-compose logs
      - name: Run tests
        working-directory: ./client
        run: yarn test
